config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  resources :flats
  root to: "flats#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/flat.rb
class Flat < ApplicationRecord
  validates :name, :address, :description, :price_per_night, :number_of_guests, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController

  def index
    # if params[:query].present?
    #   @flats = Flat.where("name LIKE ?", "%#{params[:query]}%")
    if params[:query].present?
      sql_subquery = "name LIKE :query OR address LIKE :query OR description LIKE :query"
      @flats = Flat.where(sql_subquery, query: "%#{params[:query]}%")
    else
      @flats = Flat.all
    end
  end

  def show
    @flat = Flat.find(params[:id])
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)
    if @flat.save
      redirect_to flat_path(@flat)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @flat = Flat.find(params[:id])
  end

  def update
    @flat = Flat.find(params[:id])
    if @flat.update(flat_params)
      redirect_to flat_path(@flat)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @flat = Flat.find(params[:id])
    @flat.destroy
    redirect_to flats_path
  end

  private

  def flat_params
    params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guests)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/edit.html.erb
<%= simple_form_for([@flat]) do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :description %>
  <%= f.input :price_per_night %>
  <%= f.input :number_of_guests %>
  <%= f.submit %>
<% end %>
<%= link_to "Back to Flats", "/flats", class: "btn btn-primary"%>

app/views/flats/index.html.erb
<% @flats.each do |flat| %>
<div class="wrapper">
  <h2><a href="<%= flat_path(flat) %>"><%= flat.name %></a></h2>
  <div class="image i1"></div>
  <div class="details"><h1><em><%= flat.address %></em></h1>
  <h3><%= flat.description.truncate(50) %>...</h3>
  <p>Number of Guests: <%= flat.number_of_guests %></p></div>
  <h2>$<%= flat.price_per_night %></h2>
</div>
<% end %>

app/views/flats/new.html.erb
<%= simple_form_for([@flat]) do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :description %>
  <%= f.input :price_per_night %>
  <%= f.input :number_of_guests %>
  <%= f.submit %>
<% end %>
<%= link_to "Back to flat", "/flats", class: "btn btn-primary"%>

app/views/flats/show.html.erb
<img src="" alt="">

<div class="card-trip">
  <img src="https://thumbor.forbes.com/thumbor/fit-in/x/https://www.forbes.com/advisor/wp-content/uploads/2021/08/download-7.jpg" />
  <div class="card-trip-infos">
    <div>
      <h2><%= @flat.name %></h2>
      <p><%= @flat.address %></p>
      <p><%= @flat.description %></p>
      <p>Number of Guests: <%= @flat.number_of_guests %></p>
    </div>
    <h2 class="card-trip-pricing">$<%= @flat.price_per_night %></h2>
  </div>
      <div>
    <%= link_to "Back to flats", "/flats", class: "btn btn-primary"%>
    <%= link_to "Edit this flat", edit_flat_path(@flat), class: "btn btn-primary" %>
    <%= link_to "DESTROY THIS FLAT", flat_path(@flat), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "btn btn-danger" %>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
  </head>

  <body>
  <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
      <%= image_tag("airbnb.svg", :alt => "logo") %>
    <% end %>
      <div class="row justify-content-center">
        <div class="col my-3">
          <%= form_with url: flats_path, method: :get, class: "d-flex" do %>
            <%= text_field_tag :query,
                  params[:query],
                  class: "form-control",
                  placeholder: "Type a keyword"
              %>
            <%= submit_tag "Search", name: "", class: "btn btn-light" %>
          <% end %>
        </div>
      </div>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <%# if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", "/flats", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "New Flat", "/flats/new", class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", "#", class: "dropdown-item", data: {turbo_method: :delete} %>
              <%# link_to "Log out", destroy_user_session_path, class: "dropdown-item", data: {turbo_method: :delete} %>
            </div>
          </li>
        <%# else %>
          <!--li class="nav-item"-->
            <%#= link_to "Login", new_user_session_path, class: "nav-link" %>
          <!--/li-->
        <%# end %>
      </ul>
    </div>
  </div>
</div>

    <%= yield %>
  </body>
</html>